language: csharp
solution: ./src/AreWeThereYet/AreWeThereYet/AreWeThereYet.sln
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003131
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
- chmod a+x ./Build.sh
script:
- ./Build.sh
